services:
  # Frontend Service (Static Site)
  - type: web
    name: ammex-frontend
    env: static
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    envVars:
      - key: NODE_ENV
        value: production

  # Backend Service (Web Service)
  - type: web
    name: ammex-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: f8b3a3fcef2ee384eaf1ec994b3145cd2e13e29cb5f86289cf2eaa474936dcdef0146a6460486d713e6116da98b3f7e14df24845d361b81cf7be782c6a0e5650
      - key: JWT_EXPIRE
        value: 30d
      # Add your database and other environment variables here
      # - key: DATABASE_URL
      #   sync: false  # Set this in Render dashboard
      # - key: FRONTEND_URL
      #   sync: false  # Set this in Render dashboard
